services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    networks:
      - servers
    depends_on:
      - db
      - server1
      - server2
      - server3
      - balancer

  balancer:
    command: ['lb', '--trace=true']
