networks:
  servers:

services:
  db:
    build: .
    command: 'db'
    networks:
      - servers
    ports:
      - '8070:8070'
    volumes:
      - db-data:/opt/practice-4/data

  balancer:
    build: .
    command: 'lb'
    networks:
      - servers
    ports:
      - '8090:8090'
    depends_on:
      - db

  server1:
    build: .
    command: ['server', '-team=telepuziki']
    networks:
      - servers
    ports:
      - '8080:8080'
    volumes:
      - server1-data:/opt/practice-4/data
    depends_on:
      - db

  server2:
    build: .
    command: ['server', '-team=telepuziki']
    networks:
      - servers
    ports:
      - '8081:8080'
    volumes:
      - server2-data:/opt/practice-4/data
    depends_on:
      - db

  server3:
    build: .
    command: ['server', '-team=telepuziki']
    networks:
      - servers
    ports:
      - '8082:8080'
    volumes:
      - server3-data:/opt/practice-4/data
    depends_on:
      - db

volumes:
  db-data:
  server1-data:
  server2-data:
  server3-data:
